"""
Renders the nginx server block that fronts every registered agent as one
single external entry point - GET/POST http://<gateway>/agents/<agent_id>/...
proxies straight through to that agent's own base URL, same paths
(/.well-known/agent-card.json, /) it already serves internally.

Deliberately just this agent-facing block, not agents' internal
call-to-call traffic - mesh/lib/a2a_client.py and mesh/orchestrator/
router.py are untouched; agents still call each other directly via the
Agent Registry, exactly as before. This is the layer a dashboard, support
tooling, or anything external hits, so there's one hostname/port to expose
instead of nine.

Pure functions, no I/O - see watcher.py for the loop that calls these
against a live Agent Registry snapshot and actually writes/reloads.
"""
import os
from pathlib import Path
from typing import Any, Dict, List

# Where the generated config is written. Homebrew's nginx already
# auto-includes servers/* from its own nginx.conf (confirmed live via its
# own post-install caveats) - writing straight there needs zero manual
# 'include' editing, unlike a non-Homebrew nginx install, where this should
# point at wherever that install's own http{} block includes from (override
# via ADIYAN_NGINX_SERVERS_DIR).
GENERATED_CONFIG_PATH = Path(
    os.environ.get('ADIYAN_NGINX_SERVERS_DIR', '/opt/homebrew/etc/nginx/servers')
) / 'adiyan_agents.conf'

# Homebrew's nginx defaults its own docroot server to 8080 (confirmed live
# via its post-install caveats: "so that nginx can run without sudo") - the
# gateway needs a different port so the two server blocks don't collide.
DEFAULT_GATEWAY_PORT = 8081


def render_config(agents: List[Dict[str, Any]], gateway_port: int = DEFAULT_GATEWAY_PORT) -> str:
    """One `location /agents/<agent_id>/` block per registry entry,
    stripping the /agents/<agent_id> prefix before proxying (so the target
    agent sees the same paths it always has - no agent-side changes
    needed). Deterministic output (sorted by agent_id) so a no-op registry
    poll never looks like a change to write_if_changed()."""
    header = (
        '# GENERATED by mesh/nginx/generate_config.py - do not hand-edit,\n'
        '# changes are overwritten on the next registry poll.\n'
        f'server {{\n    listen {gateway_port};\n\n'
        '    location = /agents/ {\n'
        "        default_type application/json;\n"
        '        return 200 \'{"agents": ['
        + ', '.join(f'"{a["agent_id"]}"' for a in sorted(agents, key=lambda a: a['agent_id']))
        + "]}';\n"
        '    }\n\n'
    )
    blocks = []
    for agent in sorted(agents, key=lambda a: a['agent_id']):
        agent_id = agent['agent_id']
        url = agent['url'].rstrip('/')
        blocks.append(
            f'    location /agents/{agent_id}/ {{\n'
            f'        proxy_pass {url}/;\n'
            '        proxy_set_header Host $host;\n'
            '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n'
            '    }\n'
        )
    return header + '\n'.join(blocks) + '\n}\n'


def write_if_changed(content: str, path: Path = GENERATED_CONFIG_PATH) -> bool:
    """True if the file was actually (re)written - callers use this to
    decide whether an nginx reload is even needed, so a poll that finds no
    registry change never touches nginx at all."""
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True
