#!/usr/bin/env bash
# Prints OpenWA's local dashboard API key and copies it to the clipboard -
# the file itself (penwa/data/.api-key) is auto-generated by OpenWA on its
# own first boot and re-generated if penwa/data/ is ever wiped, so this
# script reads it fresh every time rather than assuming a fixed value.
#
# Run from anywhere:
#   ./mesh/tools/openwa_key.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
KEY_FILE="$REPO_ROOT/penwa/data/.api-key"

if [ ! -f "$KEY_FILE" ]; then
    echo "No key file yet at $KEY_FILE - OpenWA hasn't booted for the first time." >&2
    echo "Start the mesh (./mesh/start_all.sh start openwa) and try again." >&2
    exit 1
fi

KEY="$(cat "$KEY_FILE")"
echo "$KEY"

if command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$KEY" | pbcopy
    echo "(copied to clipboard)" >&2
fi
